---

- name: Check /etc/multipath.conf
  stat:
    path: /etc/multipath.conf
  register: stat_multipath_conf

- name: Check service multipathd
  service:
    name: multipathd
  register: service_multipathd

- name: Remove blacklist to multipath.conf
  blockinfile:
    block: ""
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK Dell DSU Blacklist"
    path: /etc/multipath.conf
    state: absent
  when: stat_multipath_conf.stat.exists is defined and stat_multipath_conf.stat.exists

- name: Create conf.d multipath dir
  file:
    dest: /etc/multipath/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add blacklist config for dell devices into /etc/multipath/conf.d/
  copy:
    dest: /etc/multipath/conf.d/dell.conf
    src: multipath_dell.conf
    owner: root
    group: root
    mode: '0644'
  register: dell_multipath_config
  when:
    - stat_multipath_conf.stat.exists is defined and stat_multipath_conf.stat.exists
    - service_multipathd.status.ActiveState == "active"

- name: reload multipathd
  service:
    name: multipathd
    state: reloaded
  when:
    - dell_multipath_config.changed
