all:
  children:
    nerc_ocp:
      children:
        nerc_ocp_infra:
          vars:
            cluster_name: nerc-ocp-infra
          children:
            nerc_ocp_infra_controllers:
              vars:
                node_role: openshift_controller
                vendor: lenovo
              hosts:
                ctl-0.nerc-ocp-infra.rc.fas.harvard.edu:
                  location:
                    row: 7
                    pod: C
                    cage: 3
                    unit: 9
                ctl-1.nerc-ocp-infra.rc.fas.harvard.edu:
                  location:
                    row: 7
                    pod: C
                    cage: 3
                    unit: 9
                ctl-2.nerc-ocp-infra.rc.fas.harvard.edu:
                  location:
                    row: 7
                    pod: C
                    cage: 3
                    unit: 11
