- name: Get current IPMILan value
  delegate_to: "{{ bmc_addr }}"
  raw: >-
    racadm get idrac.ipmilan.enable
  register: get_result
  changed_when: false
  failed_when: >-
    "ERROR" in get_result.stdout

- name: Enable IPMILan
  when: >-
    "Enable=Enabled" not in get_result.stdout_lines[1]
  delegate_to: "{{ bmc_addr }}"
  raw: >-
    racadm set idrac.ipmilan.enable 1
  register: set_result
  failed_when: >-
    "ERROR" in set_result.stdout
