---
galaxy_info:
  author: Kalle Happonen
  description: This repository automates Dell firmware upgradation process using ansible
  company: CSC - IT Center for Science Ltd.
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  categories:
  - system
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
