- hosts: nerc_ocp_prod_workers
  vars: 
    upgrade_categories: "BIOS,iDRAC,ESM"
    dell_dsu_repo_install: false
    dell_dsu_assert: false
    dell_dsu_manage_multipath_config: false
    dell_dsu_rollout_gpg_keys: false
    bmc_credentials: "{{ lookup('amazon.aws.aws_secret', 'cluster/nerc/ocp/bmc') | from_json }}"
    bmc_user: "{{ bmc_credentials.username }}"
    bmc_pass: "{{ bmc_credentials.password }}"
  roles:
    - { role: ansible-role-dell-firmware-upgrade }
  tasks:
    - name: Disable host header check
      delegate_to: "{{ bmc_addr }}"
      raw: >-
        racadm set idrac.webserver.HostHeaderCheck 0
      register: result
      failed_when: >-
        "Object value modified successfully" not in result.stdout