- hosts: nerc_ocp_prod&vendor_dell
  vars: 
    upgrade_categories: "BIOS,iDRAC,ESM"
    dell_dsu_repo_install: true
    bmc_credentials: "{{ lookup('amazon.aws.aws_secret', 'cluster/nerc/ocp/bmc') | from_json }}"
    ansible_user: "{{ bmc_credentials.username }}"
    ansible_ssh_pass: "{{ bmc_credentials.password }}"
  roles:
    - { role: ansible-role-dell-firmware-upgrade }
  tasks:
    - name: Disable host header check
      delegate_to: "{{ bmc_addr }}"
      raw: >-
        racadm set idrac.webserver.HostHeaderCheck 0
      register: result
      failed_when: >-
        "Object value modified successfully" not in result.stdout