- hosts: localhost
  gather_facts: false
  vars:
    common_names: 
      - api.nerc-ocp-prod.rc.fas.harvard.edu
      - apps.nerc-ocp-prod.rc.fas.harvard.edu
    country_name: US
    organization_name: NERC
    state_or_province_name: MA

  tasks:
    - name: generate private keys
      openssl_privatekey:
        path: "/etc/ssl/private/{{ item }}.pem"
      loop: "{{ common_names }}"

  - name: generate private keys
        openssl_csr:
          path: "/etc/ssl/csr/{{ item }}.csr"
          privatekey_path: "/etc/ssl/private/{{ item }}.pem"
          common_name: "{{ item }}"
          country_name: "{{ country_name }}"
          organization_name: "{{ organization_name }}"
          state_or_province_name: "{{ state_or_province_name }}"
        loop: "{{ common_names }}"
